### PR TITLE
Fix data movement task dependencies with clang-formatting

### PR DESCRIPTION
**Pull request by nicelhc13**
@yinengy found and reported this bug:

```
a.print_overview()
@spawn(ts[5], placement=gpu(1), inout=[(a,0)])
def check_array_evict():
    a.print_overview()

@spawn(ts[7], dependencies=[ts[5]], placement=[gpu(1)], input=[(a, 0)])
def check_array_evict2():
    a.print_overview()

@spawn(ts[8], dependencies=[ts[7]], placement=[gpu(2)], input=[(a, 0)])
def check_array_evict3():
    a.print_overview()
```

In this case, `ts[8]`'s datamovement task runs before `ts[5]`.
This is because the current data move task dependency is intersection between compute task and parray's referrers. 
However, in this case, `ts[8]`'s dependency is `ts[7]` and `a`'s dependency is `ts[5]`, and so, there is no intersection.
In order to fix this case, I make the parray's referrers the last task accessing it on OUT or INOUT permission.
Whenever this task is being spawned, the old referrers are cleared. 
For correctness, tasks should be spawned in program execution order, but this is not new and so I think it is ok.

### CODE REVIEW

**Comment by wlruys** [comment]
We need to fix this for NUWEST, will try my best to think of a solution to change data movement dependency semantics.

**Comment by nicelhc13** [comment]
working on it from today

**Comment by nicelhc13** [comment]
To sum up, here is the possible solution:
Delay adding a task itself to a parray list from the creation phase to right after task mapping phase is completed; due to the ordering constraint that parents have been mapped before a task can be mapped, we can guarantee the task list is valid.
Then, we remove this when a compute task is completed.

Mapping policy actually gets more accurate information (it was your concern, wasn't it? Otherwise, I am missing something)

So when we create a data move task for task 8, task 5 should be on the list.
then task 5 will be included in task 8.

**Comment by nicelhc13** [comment]
I changed data move task creation and its dependency creation. Basically, instead of finding task list of a parray and compute dependency tasks, now each task sets dependency lists for each parray for dependent tasks and propagates it if a dependent task accesses the parray with read-only permission. I am not 100% for sure if this is not wrong but the bug case, cholesky, and sorting seem working correctly.

**Review by wlruys — APPROVED** [review]
I think I understand this after our call. It seems like a good solution while we resolve other data semantics.

**Pull request merged**
